" Load all plugins
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-sensible'
Plug 'roxma/nvim-yarp'
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'flazz/vim-colorschemes'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'majutsushi/tagbar'
Plug 'ervandew/supertab'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'w0rp/ale'
Plug 'Shougo/deoplete.nvim'
Plug 'Yggdroot/indentLine'
Plug 'davidhalter/jedi-vim'
Plug 'zchee/deoplete-jedi'
Plug 'leafgarland/typescript-vim'
Plug 'sheerun/vim-polyglot'
Plug 'farmergreg/vim-lastplace'
call plug#end()

" Use Vim defaults
set nocompatible

let mapleader=" "

" Colorscheme settings.
let g:zenburn_transparent = 1
colorscheme zenburn
hi Normal guibg=#3f3f3f ctermbg=None

" Minimal GUI, window size, font
if has('gui_running')
  set guioptions=ac
  set columns=132 lines=43
  set guifont=InconsolataGo\ Nerd\ Font\ 10
endif

" Numbered lines.
set number

" Highlight cursor line.
augroup CursorLine
  au!
  au VimEnter,WinEnter,BufWinEnter,FocusGained * setlocal cursorline
  au VimEnter,WinEnter,BufWinEnter,FocusGained * setlocal cursorcolumn
  au FocusLost,WinLeave * setlocal nocursorline
  au FocusLost,WinLeave * setlocal nocursorcolumn
augroup END

" Mouse usage enabled in all modes.
set mouse=a
" Set xterm2 mouse mode to allow resizing of splits with mouse inside Tmux.
set ttymouse=xterm2

" Use system clipboard by default
set clipboard=unnamed

" Control character highlighting.
set list listchars=tab:⇥⇥,eol:↵

" Tab settings.
set expandtab
set shiftwidth=4
set ts=4

" Parens matching.
set showmatch
set matchtime=5

" No screen redrawing during macros.
set lazyredraw

" Search settings.
set incsearch
set hlsearch
set ignorecase
set smartcase

" No extra files.
set noswapfile
set nobackup

" WiLd menu.
set wildmenu
set wildignore=*.o,*~,*.pyc

" Aesthetics.
set title

" No annoying alerts.
set noerrorbells
set novisualbell

" Make trailing whitespace annoyingly highlighted.
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" Easy cycling of buffers
nmap <C-tab> :bnext<CR>

" Prettify airline
let g:airline_powerline_fonts = 1

" Map tagbar
nmap <silent> <leader>o :TagbarOpenAutoClose<CR>

" Supertab scrolls down the list of completions
let g:SuperTabDefaultCompletionType = "<c-n>"

" Map FZF
nmap <silent> <leader>f :Files<CR>
nmap <silent> <leader>b :Buffers<CR>
nmap <silent> <leader>l :Lines<CR>
nmap <silent> <leader>t :Tags<CR>

" Better ALE interface
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)
nmap <silent> <leader>x <Plug>(ale_fix)
nmap <silent> <leader>d <Plug>(ale_go_to_definition)
let g:ale_sign_error = '✗'
let g:ale_sign_warning = '!'

" Open NERDTree if vim arg is a directory
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif
nmap <leader>n :NERDTreeToggle<CR>
nmap <leader>e :NERDTreeFind<CR>

" Set better vertical bar for indentation
let g:indentLine_char = ':'

" Use deoplete-jedi completion
let g:deoplete#enable_at_startup = 1
let g:jedi#completions_enabled = 0

" Configure fixers and linters
 let g:ale_fixers = {
  \   'c': ['clang-format', 'remove_trailing_lines', 'trim_whitespace'],
  \   'python': ['black', 'isort', 'remove_trailing_lines', 'trim_whitespace'],
  \   'javascript': ['eslint', 'remove_trailing_lines', 'trim_whitespace'],
  \   'typescript': ['eslint', 'remove_trailing_lines', 'trim_whitespace'],
  \   'json': ['prettier', 'remove_trailing_lines', 'trim_whitespace'],
  \   'yaml': ['prettier', 'remove_trailing_lines', 'trim_whitespace'],
  \   'scss': ['stylelint', 'remove_trailing_lines', 'trim_whitespace'],
  \   'html': ['html-beautify', 'remove_trailing_lines', 'trim_whitespace']
  \}

 let g:ale_c_parse_makefile = 1
 let g:ale_c_parse_compile_commands = 1
 let g:ale_c_clangformat_options = '-style="{BasedOnStyle: llvm, IndentWidth: 4}" '
 let g:ale_python_pylint_options = '--load-plugins pylint_django -dC0330'
 let g:ale_javascript_prettier_options = '--tab-width 4'
